#!/usr/bin/env python3

CLOUD_NAME = 'TEST_CLOUD_NAME'
API_KEY = 'TEST_API_KEY'
API_SECRET = 'TEST_API_SECRET'
JWT_SECRET = 'testsecret'
FOLDER = 'TEST_FOLDER'
IMAGE_BASE64 = \
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA' + \
    'AAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIA' + \
    'XDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=='
IMAGE_BASE64_NO_PREFIX = \
    'iVBORw0KGgoAAAANSUhEUgAA' + \
    'AAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIA' + \
    'XDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=='
IMAGE_BASE64_BYTES = IMAGE_BASE64_NO_PREFIX.encode()
PUBLIC_ID = 'TEST_PUBLIC_ID'
IMAGE_URL = 'http://example.com/image.png'
